name: CommandTimer
version: 3.0
description: This plugin allows you to schedule commands that will be executed
main: me.playbosswar.com.Main
author: PlayBossWar
commands:
  commandtimer:
    usage: /<command>
    description: List all commands