#GENERAL
timeonload: true

settings:
  tasks:
    #'1':
     # commands:
      #- say This message will only show up at a specific time.
      #onhour: true
      #time: '13:49'
      #seconds: 60
      #onload: false
    #'2':
     # commands:
      #- say This message appears every 10 seconds
      #onhour: false
      #time: '13:49'
      #seconds: 10
      #onload: false
      #gender: 'player'
      #permission: 'permission.test.commandtimer'
      #random: 50
    #'3':
      #commands:
      #- say This message appears after 5 seconds after restart but do not show up again after the restart/reload
     # onhour: false
     #time: '13:49'
     #seconds: 5
     # onload: true
    #'4':
      #commands:
      #- say This message appears every 10 seconds every wednesday
      #onhour: false
      #onday: true
      #days:
      #- 'WEDNESDAY'
      #time: '13:49'
      #seconds: 10
      #onload: false